application.name = se1-play

application.version = 1.0.0-SNAPSHOT

application.args = this is b2-numbers

numbers.args = command=sum numbers=1,2,3,4,5

numbers.data.small = 1 2 3 4 5

numbers.data.mixed = -5 -2 -1 0 1 2 3 4 5

numbers.data.dup = 1 2 2 3 4 4 5
